name: spols
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4.0
- bioconductor-bsseq=1.14.0
- bioconductor-m3drop=1.4.0
- bioconductor-monocle=2.6.0
- bioconductor-rgraphviz=2.22.0
- bioconductor-sc3=1.7.6
- bioconductor-scater=1.6.0
- bioconductor-scran=1.6.2
- bioconductor-topgo=2.30.0
- bioconductor-tscan=1.16.0
- ipykernel=4.7.0
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.3.3
- jupyter_nbextensions_configurator=0.2.8
- nb_conda=2.2.1
- notebook=5.2.2
- pip=9.0.1
- pytest=3.3.1
- python=3.6.3
- r-base=3.4.1
- r-data.table=1.10.4
- r-dplyr=0.7.0
- r-gdata=2.17.0
- r-ggally=1.3.2
- r-ggplot2=2.2.1
- r-ggsci=2.7
- r-hmisc=4.0
- r-irkernel=0.8.11
- r-magrittr=1.5
- r-readxl=1.0.0
- r-essentials=1.6.0
- r-recommended=3.4.1
- r-rtsne=0.13
- r-tidyr=0.6.3
- rstudio=1.0.153
