name: base
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - jupyter
  - jupyter_nbextensions_configurator
  - louvain
  - matplotlib
  - matplotlib-venn
  - notebook
  - numba
  - numexpr
  - numpy
  - openpyxl
  - pandas
  - python-igraph
  - r-data.table
  - r-magrittr
  - r-matrix
  - r-reticulate
  - rpy2
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip:
    - multicoretsne
